FROM nginx:latest

RUN apt-get update && \
  apt install php-fpm php-json php-curl php-cgi php-mysql php-gd php-pgsql -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN usermod -a -G www-data nginx

COPY ntunnel/ntunnel_*.php /usr/share/nginx/html/
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

COPY start.sh /start.sh
RUN chmod +x /start.sh
CMD ["/start.sh"]