FROM centos:6.9
#设置时间
RUN set -ex \
	&& rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
#设置语言
ENV LANG=en_US.utf8

#使用合光的yum源
RUN set -ex \
	&& rm -rf /etc/yum.repos.d/* \
	&& curl -o /etc/yum.repos.d/uairobot.repo http://download.uairobot.com/yum/repo/centos-6/uairobot-base.repo
#安装tomat
RUN set -ex \
	&& yum -y install tomcat \
	&& yum clean all
#释出端口
EXPOSE 8080
#启动命令
COPY docker_tomcat_run.sh /docker_tomcat_run.sh
RUN chmod u+x /docker_tomcat_run.sh
CMD ["/docker_tomcat_run.sh"]