#构建ibot_cluser	
FROM centos:6.9
#设置时间
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
#设置编码
ENV LANG=en_US.utf8
#使用合光的yum源
RUN set -ex \
	&& rm -rf /etc/yum.repos.d/* \
	&& curl -o /etc/yum.repos.d/uairobot-ip.repo http://download.uairobot.com/yum/repo/centos-6/uairobot-ip.repo
	
ENV CLUSTER_DIR=/usr/local/ibotcluster
#工作目录,会自动创建改目录
WORKDIR $CLUSTER_DIR

ENV MYSQL_CONF=/etc/my.cnf
ENV MYSQL_ROOT_PASSWORD=root
#安装mysql-server
RUN set -ex \
	&& yum -y install mysql mysql-server \
	&& yum clean all

ENV JAVA_HOME /usr/java/jdk1.6.0_45
ENV PATH=$PATH:$JAVA_HOME/bin/
#jdk下载地址
ENV jdk_file=jdk-6u45-linux-x64.bin
ENV jdk_download_url=http://download.uairobot.com/jdk/1.6/$jdk_file
#安装jdk1.6
RUN set -ex \
	&& curl -O ${jdk_download_url} \
	&& chmod u+x ${jdk_file} && ./${jdk_file} && rm -rf ${jdk_file} \
	&& mkdir /usr/java && mv jdk1.6.0_45 /usr/java 
#mnamger和robot目录
ENV ROBOT_DIR=$CLUSTER_DIR/robot
ENV MANAGER_DIR=$CLUSTER_DIR/manager
ENV ROBOT_PROPERTIES=$ROBOT_DIR/webapps/robot/WEB-INF/classes/app.properties
ENV MANAGER_PROPERTIES=$MANAGER_DIR/webapps/manager/WEB-INF/classes/app.properties
#jetty地址
ENV jetty_file=jetty-6.tar.gz
ENV jetty_downloa_url=http://download.uairobot.com/jetty/$jetty_file

#robot和manager下载地址
ENV robot_file=robot-20181112.tar.gz
ENV robot_download_url=http://download.uairobot.com/ibot/ibot_9.0_suite/ibot9_20181112/$robot_file
ENV manager_file=manager-20181112.tar.gz
ENV manager_download_url=http://download.uairobot.com/ibot/ibot_9.0_suite/ibot9_20181112/$manager_file
#下载 jetty-robot 和 jetty-manager
RUN set -ex \
	&& curl -O ${jetty_downloa_url} \
	&& tar -zxf ${jetty_file} && mv jetty-6 $ROBOT_DIR \
	&& tar -zxf ${jetty_file} && mv jetty-6 $MANAGER_DIR \
	&& rm -rf ${jetty_file} \
	&& curl -O ${robot_download_url} \
	&& curl -O ${manager_download_url} \
	&& tar -xf ${robot_file} -C $ROBOT_DIR/webapps \
	&& rm -rf ${robot_file} \
	&& tar -xf ${manager_file} -C $MANAGER_DIR/webapps \
	&& rm -rf ${manager_file}
#设置端口号,默认 8000, robot 80 manager  81
RUN set -ex \
	&& sed -i.ori 's#default="8000"#default="80"#' $ROBOT_DIR/etc/jetty.xml \
	&& sed -i.ori 's#default="8000"#default="81"#' $MANAGER_DIR/etc/jetty.xml
#设置jetty.sh,APP_HOME和JETTY_HOME已经通过其他方式处理,不需要设置
#设置 robot配置文件
RUN set -ex \
	&& sed -i.ori 's#ai.addr=172.16.8.35:90#ai.addr=##' $ROBOT_PROPERTIES \
	&& sed -i.ori 's#172.16.8.35:3306/manager_test#127.0.0.1:3306/ibot_cluster#' $ROBOT_PROPERTIES 
#设置 manager配置文件	
RUN set -ex \
	&& sed -i.ori 's#ai.addr=172.16.8.35:90#ai.addr=#' $MANAGER_PROPERTIES \
	&& sed -i.ori 's#172.16.8.35:3306/manager_test#127.0.0.1:3306/ibot_cluster#' $MANAGER_PROPERTIES \
	&& sed -i.ori 's#robot.context_path=http://172.16.8.35/robot/#robot.context_path=http://127.0.0.1/robot/#' $MANAGER_PROPERTIES \
	&& sed -i.ori 's#robot.context_path.internal=#robot.context_path.internal=http://127.0.0.1/robot/#' $MANAGER_PROPERTIES
#启用集群功能
RUN set -ex \
	&& sed -i.ori 's#ibot.mgr.clusterEnabled=#ibot.mgr.clusterEnabled=true#' $MANAGER_PROPERTIES \
	&& sed -i.ori 's#-Xconcurrentio#-Xconcurrentio -Dibot.mgr.clusterEnabled=true#' $ROBOT_DIR/jetty.sh
#启用h2,内置数据源
RUN set -ex \
	&& sed -i.ori 's#-Xconcurrentio#-Xconcurrentio -Dh2db.port=9100#' $ROBOT_DIR/jetty.sh \
	&& sed -i.ori 's#-Xconcurrentio#-Xconcurrentio -Dh2db.port=9100#' $MANAGER_DIR/jetty.sh
#设置mysql配置,创建用户名和密码,并初始化数据库,测试没有出现乱码
RUN set -ex \
	&& sed -i '/\[mysqld\]/a\character-set-server=utf8 #utf-8编码' $MYSQL_CONF \
	&& sed -i '/\[mysqld\]/a\skip-name-resolve #去除名称解析' $MYSQL_CONF \
	&& sed -i '/\[mysqld\]/a\lower_case_table_names=1 #忽略表名大小写' $MYSQL_CONF \
	&& sed -i '/\[mysqld\]/a\default-storage-engine=INNODB #默认使用innodb引擎' $MYSQL_CONF \
	&& /etc/init.d/mysqld start \
	&& mysql -e "update mysql.user set password=PASSWORD('${MYSQL_ROOT_PASSWORD}');" \
	&& mysql -e "flush privileges;" \
	&& mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "create database ibot_cluster;" \
	&& curl -O http://download.uairobot.com/ibot/ibot_9.0_suite/ibot9_20181112/sql/ibot_cluster_20181112.sql \
	&& mysql -uroot -p${MYSQL_ROOT_PASSWORD} ibot_cluster < ibot_cluster_20181112.sql \
	&& rm -rf ibot_cluster_20181112.sql
#安装ffmpeg
RUN set -ex \
	&& yum -y install gcc gcc-c++ make yasm && yum clean all \
	&& curl -O http://download.uairobot.com/ffmpeg/2.7.2/ffmpeg-2.7.2.tar.gz \
	&& tar -zxf ffmpeg-2.7.2.tar.gz && cd ffmpeg-2.7.2 \
	&& ./configure --enable-shared --disable-yasm \
	&& make && make install \
	&& cd .. && rm -rf ffmpeg-2.7.2 ffmpeg-2.7.2.tar.gz \
	&& echo "/usr/local/lib/" >> /etc/ld.so.conf
#添加cloud支持
ENV ROBOT_ICLOUD_JAR_NAME=robot-icloud-api-1.0.jar
ENV ROBOT_ICLOUD_JAR_URL=http://download.uairobot.com/ibot_cloud/20170511/attachment/$ROBOT_ICLOUD_JAR_NAME
ENV APP_NLP_SERVICE_LOG_SQL=http://download.uairobot.com/ibot_cloud/20170511/attachment/app_nlp_service_log.sql
RUN set -ex \
	&& curl -o $ROBOT_DIR/webapps/robot/WEB-INF/lib/$ROBOT_ICLOUD_JAR_NAME $ROBOT_ICLOUD_JAR_URL \
	&& curl -O $APP_NLP_SERVICE_LOG_SQL
	&& curl -O http://download.uairobot.com/ibot_cloud/20170511/robot-root/robot-root.tar.gz
	
#添加日志输出
RUN set -ex \
    && ln -sf /dev/stdout /usr/local/ibotcluster/manager/logs/stdout.log \
    && ln -sf /dev/stderr /usr/local/ibotcluster/manager/logs/stdout.log
	
#映射端口
EXPOSE 3306/tcp 80/tcp 81/tcp
#启动服务
COPY ibot_cluster_start.sh /etc/init.d/ibot_cluster_start.sh
RUN chmod u+x /etc/init.d/ibot_cluster_start.sh
CMD ["/etc/init.d/ibot_cluster_start.sh"]