#构建 litongjava/xrdp:1.0
FROM centos:7.3.1611
#设置时间
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
#使用ali yum源
RUN set -ex \
  && rm -rf /etc/yum.repos.d/* \
  && curl -o /etc/yum.repos.d/Centos-7.repo http://mirrors.aliyun.com/repo/Centos-7.repo \
  && curl -o /etc/yum.repos.d/epel-7.repo http://mirrors.aliyun.com/repo/epel-7.repo