FROM litongjava/jdk:21_0_6-stable-slim

RUN curl -O -L https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz && \
    mkdir -p /usr/maven && \
    tar -xf apache-maven-3.8.8-bin.tar.gz -C /usr/maven && \
    rm apache-maven-3.8.8-bin.tar.gz

# Set environment variables for Java and Maven
ENV JAVA_HOME=/usr/java/jdk-21.0.6 \
    MVN_HOME=/usr/maven/apache-maven-3.8.8 \
    PATH=/usr/java/jdk-21.0.6/bin:/usr/maven/apache-maven-3.8.8/bin:$PATH

