#httpd
FROM debian:jessie
#设置时间
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
#添加字符集为UTF-8
ENV LANG=C.UTF-8
#设置aliyun apt源
RUN set -ex \
    && { \
        echo 'deb http://mirrors.aliyun.com/debian/ jessie main non-free contrib'; \
        echo 'deb http://mirrors.aliyun.com/debian/ jessie-proposed-updates main non-free contrib'; \
        echo 'deb-src http://mirrors.aliyun.com/debian/ jessie main non-free contrib'; \
        echo 'deb-src http://mirrors.aliyun.com/debian/ jessie-proposed-updates main non-free contrib'; \
    } > /etc/apt/sources.list

#apache2安装目录
ENV HTTPD_PREFIX /usr/local/apache2
WORKDIR $HTTPD_PREFIX
ENV PATH $PATH:$HTTPD_PREFIX/bin

#创建目录,设置权限,debian:jessie自带 www-data用户
RUN set -ex \
	&& mkdir -p "$HTTPD_PREFIX" \
    && chown www-data:www-data "$HTTPD_PREFIX"

#安装apache依赖
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libapr1 libaprutil1 libaprutil1-ldap libapr1-dev libaprutil1-dev libpcre++0 libssl1.0.0 \
    && rm -r /var/lib/apt/lists/*

ENV HTTPD_VERSION 2.4.37
ENV HTTPD_BZ2_URL http://download.uairobot.com/httpd/$HTTPD_VERSION/httpd-$HTTPD_VERSION.tar.bz2

#安装编译依赖环境,下载安装包,校验,编译安装,移除依赖必须一步完成
RUN buildDeps='ca-certificates curl bzip2 gcc libpcre++-dev libssl-dev make' \
    set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends $buildDeps \
    && rm -r /var/lib/apt/lists/* \
    && curl -fSL "$HTTPD_BZ2_URL" -o httpd.tar.bz2 \
    && curl -fSL "$HTTPD_BZ2_URL.asc" -o httpd.tar.bz2.asc \
    && export GNUPGHOME="$(mktemp -d)" \
    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 1AD84DFF \
    && gpg --batch --verify httpd.tar.bz2.asc httpd.tar.bz2 \
    && rm -r "$GNUPGHOME" httpd.tar.bz2.asc \
    \
    && mkdir -p src \
    && tar -xvf httpd.tar.bz2 -C src --strip-components=1 \
    && rm httpd.tar.bz2 \
    && cd src \
    && ./configure --prefix="$HTTPD_PREFIX" --enable-mods-shared=reallyall \
    && make -j"$(nproc)" \
    && make install \
    && cd .. \
    && rm -r src \
    \
    && sed -ri \
        -e 's!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g' \
        -e 's!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g' \
        "$HTTPD_PREFIX/conf/httpd.conf" \
	&& echo "IndexOptions Charset=UTF-8" >> "$HTTPD_PREFIX/conf/httpd.conf" \
    \
    && apt-get purge -y --auto-remove $buildDeps

COPY httpd-foreground /usr/local/bin/
RUN chmod +x /usr/local/bin/httpd-foreground

EXPOSE 80
CMD ["httpd-foreground"]