#jdk1.6
FROM centos:6.9
#设置时间
RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
#设置编码
ENV LANG=en_US.utf8
#使用合光的yum源
RUN set -ex \
	&& rm -rf /etc/yum.repos.d/* \
	&& curl -o /etc/yum.repos.d/uairobot.repo http://download.uairobot.com/yum/repo/centos-6/uairobot-base.repo
ENV JAVA_HOME=/usr/java/jdk1.6.0_45
ENV PATH=$JAVA_HOME/bin:$PATH
#jdk下载地址
ENV jdk_file=jdk-6u45-linux-x64.bin
ENV jdk_download_url=http://download.uairobot.com/jdk/1.6/$jdk_file
RUN set -ex \
	&& curl -O ${jdk_download_url} \
	&& chmod u+x ${jdk_file} && ./${jdk_file} && rm -rf ${jdk_file} \
	&& mkdir /usr/java && mv jdk1.6.0_45 /usr/java